// Frozen from baseline ffc07ec before the declarative interpreter was introduced.
// UUID-keyed lanes substitute their fixture catalog UUID; all other strings are literal.
let programDefinitionGolden: [(day: Int, exercise: String, sets: Int, muscle: String, key: String)] = [
    (0, "Flat DB Press", 2, "chest", "openlift.clustered-hypertrophy.v1.cluster-1.chest.b"),
    (0, "Lat Pulldown", 2, "back", "openlift.clustered-hypertrophy.v1.cluster-1.back.a"),
    (0, "Overhead Cable Extension", 3, "triceps", "openlift.clustered-hypertrophy.v1.cluster-2.triceps.a"),
    (0, "Incline Curl", 3, "biceps", "openlift.clustered-hypertrophy.v1.cluster-2.biceps.a"),
    (1, "Seated Cable Flye", 2, "chest", "openlift.clustered-hypertrophy.v1.cluster-1.chest.c"),
    (1, "CS DB Row", 2, "back", "openlift.clustered-hypertrophy.v6.cluster-1.back.dumbbell-row"),
    (1, "Cable Pushdown", 3, "triceps", "openlift.clustered-hypertrophy.v1.cluster-2.triceps.b"),
    (1, "DB Preacher Curl", 3, "biceps", "openlift.clustered-hypertrophy.v1.cluster-2.biceps.b"),
    (2, "Incline DB Press", 2, "chest", "openlift.clustered-hypertrophy.v1.cluster-1.chest.a"),
    (2, "SA Lat Pulldown", 2, "back", "openlift.clustered-hypertrophy.v6.cluster-1.back.single-arm-pulldown"),
    (2, "DB Skullcrusher", 3, "triceps", "openlift.clustered-hypertrophy.v1.cluster-2.triceps.c"),
    (2, "Bayesian Curl", 3, "biceps", "openlift.clustered-hypertrophy.v1.cluster-2.biceps.c"),
    (3, "Incline DB Flye", 2, "chest", "openlift.clustered-hypertrophy.v1.cluster-1.chest.c"),
    (3, "SA CS Cable Row", 2, "back", "openlift.clustered-hypertrophy.v1.cluster-1.back.c"),
    (3, "Overhead SA Cable Extension", 2, "triceps", "openlift.clustered-hypertrophy.v8.movement.triceps.{exerciseID}"),
    (3, "Seated DB Hammer Curl", 2, "biceps", "openlift.clustered-hypertrophy.v8.movement.biceps.{exerciseID}"),
    (4, "Back Extension", 3, "hamstrings", "openlift.clustered-hypertrophy.v7.movement.legs.{exerciseID}"),
    (5, "Belt Squat", 3, "quads", "openlift.clustered-hypertrophy.v7.movement.legs.{exerciseID}"),
    (6, "Stiff-Leg Deadlift", 3, "hamstrings", "openlift.clustered-hypertrophy.v7.movement.legs.{exerciseID}"),
    (7, "Bulgarian Split Squat", 3, "quads", "openlift.clustered-hypertrophy.v7.movement.legs.{exerciseID}"),
    (8, "Reverse Hyper", 2, "hamstrings", "openlift.clustered-hypertrophy.v7.movement.legs.{exerciseID}"),
    (9, "Safety Bar Squat", 3, "quads", "openlift.clustered-hypertrophy.v7.movement.legs.{exerciseID}"),
    (10, "Leg Curl", 3, "hamstrings", "openlift.clustered-hypertrophy.v7.movement.legs.{exerciseID}"),
    (11, "Leg Extension", 2, "quads", "openlift.clustered-hypertrophy.v7.movement.legs.{exerciseID}"),
    (12, "Incline Side-Lying DB Lateral Raise", 2, "sideDelts", "openlift.clustered-hypertrophy.v7.movement.shoulders.{exerciseID}"),
    (12, "Stair Calves", 3, "calves", "openlift.clustered-hypertrophy.v7.movement.calves.{exerciseID}"),
    (12, "Seated DB Shrugs", 2, "traps", "openlift.clustered-hypertrophy.v3.cluster-3.traps.seated-dumbbell-shrug"),
    (13, "Super ROM DB Lateral Raise", 2, "sideDelts", "openlift.clustered-hypertrophy.v7.movement.shoulders.{exerciseID}"),
    (13, "Bench-Supported Cable Wrist Curl (Supinated)", 3, "forearms", "openlift.clustered-hypertrophy.v1.cluster-3.calves-forearms.b"),
    (14, "Cable Lateral Raise", 2, "sideDelts", "openlift.clustered-hypertrophy.v7.movement.shoulders.{exerciseID}"),
    (14, "Stair Calves", 3, "calves", "openlift.clustered-hypertrophy.v7.movement.calves.{exerciseID}"),
    (14, "Seated DB Shrugs", 2, "traps", "openlift.clustered-hypertrophy.v3.cluster-3.traps.seated-dumbbell-shrug"),
    (15, "Incline Side-Lying DB Lateral Raise", 2, "sideDelts", "openlift.clustered-hypertrophy.v7.movement.shoulders.{exerciseID}"),
    (15, "Bench-Supported Cable Wrist Extension (Pronated)", 3, "forearms", "openlift.clustered-hypertrophy.v1.cluster-3.calves-forearms.d"),
    (16, "Super ROM DB Lateral Raise", 2, "sideDelts", "openlift.clustered-hypertrophy.v7.movement.shoulders.{exerciseID}"),
    (16, "Stair Calves", 3, "calves", "openlift.clustered-hypertrophy.v7.movement.calves.{exerciseID}"),
    (16, "Seated DB Shrugs", 2, "traps", "openlift.clustered-hypertrophy.v3.cluster-3.traps.seated-dumbbell-shrug"),
    (17, "Cable Lateral Raise", 2, "sideDelts", "openlift.clustered-hypertrophy.v7.movement.shoulders.{exerciseID}"),
    (17, "Captain of Crush", 3, "forearms", "openlift.clustered-hypertrophy.v1.cluster-3.calves-forearms.f"),
]
